# Generated by Django 2.1.3 on 2018-12-02 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_with_numeric_input',
            name='correct_answer',
            field=models.CharField(default='', max_length=10, verbose_name='Correct Answer'),
        ),
        migrations.AddField(
            model_name='answer_with_text_input',
            name='correct_answer',
            field=models.CharField(default='', max_length=300, verbose_name='Correct Answer'),
        ),
    ]
