# Generated by Django 2.1.3 on 2018-12-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181202_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simple_question',
            name='question',
            field=models.TextField(verbose_name='Question'),
        ),
    ]
