# Generated by Django 2.0.9 on 2018-12-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181202_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_with_text_input',
            name='correct_answer',
            field=models.CharField(default='', max_length=400, verbose_name='Correct Answer'),
        ),
    ]
