# Generated by Django 2.0.9 on 2018-12-08 02:24

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181208_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simple_question',
            name='question',
            field=tinymce.models.HTMLField(verbose_name='Question'),
        ),
    ]
