# Generated by Django 2.0.9 on 2018-12-08 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181208_0748'),
        ('gre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssaySet',
            fields=[
                ('essay_set_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Essay_Set')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.essay_set',),
        ),
        migrations.CreateModel(
            name='QuantativeSet',
            fields=[
                ('quant_set_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Quant_Set')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.quant_set',),
        ),
        migrations.CreateModel(
            name='VerbalSet',
            fields=[
                ('verbal_set_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Verbal_Set')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.verbal_set',),
        ),
    ]
